[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# El output de Vite ya viene empaquetado. No reprocesar CSS/JS.
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
